// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjzUwbufmxBQPNSaKVBIM68JXjH7y88Wk',
    appId: '1:759264872546:web:b745b92062ed735f93a93b',
    messagingSenderId: '759264872546',
    projectId: 'aura-list',
    authDomain: 'aura-list.firebaseapp.com',
    storageBucket: 'aura-list.firebasestorage.app',
    measurementId: 'G-SW9ZNY799J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmL_Z4qj1uAmbbpwWlCFtZgDRGJy03Qw',
    appId: '1:759264872546:android:759cc9f754fc74b493a93b',
    messagingSenderId: '759264872546',
    projectId: 'aura-list',
    storageBucket: 'aura-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeycStAnUYqknGYxPef7wkZcD_XryZQHo',
    appId: '1:759264872546:ios:5cb1655051db5d4f93a93b',
    messagingSenderId: '759264872546',
    projectId: 'aura-list',
    storageBucket: 'aura-list.firebasestorage.app',
    iosClientId: '759264872546-3i9clp6siu3vub7mphiqpfjemuqars6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.checklistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjzUwbufmxBQPNSaKVBIM68JXjH7y88Wk',
    appId: '1:759264872546:web:6162752f920d4b7793a93b',
    messagingSenderId: '759264872546',
    projectId: 'aura-list',
    authDomain: 'aura-list.firebaseapp.com',
    storageBucket: 'aura-list.firebasestorage.app',
    measurementId: 'G-3N3F9E997V',
  );
}
